# Generated by Django 4.1.7 on 2023-03-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default=None, upload_to='subjects/%Y/%m'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(default=None, upload_to='lessons/%Y/%m')),
                ('content', models.TextField(blank=True, max_length=255, null=True)),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
